apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: monitoring
  labels:
      env: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
      requests:
        storage: 20Gi
  storageClassName: gp2

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
      name: monitoring
